channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.5
  - biopython=1.69
  - numpy=1.13.1
  - edlib=1.2.3
  - cyvcf2
  - requests
  - click
  - pip:
    - pyinterval==1.2.0
